import type { MechBlueprint, MechSimulationResult } from '../types';

const STORAGE_KEY = 'mechlab_blueprints';
const CURRENT_PROJECT_KEY = 'mechlab_current_project';

export class ProjectService {

    /**
     * Save a blueprint to localStorage
     */
    static saveBlueprint(blueprint: MechBlueprint): void {
        const blueprints = this.getAllBlueprints();
        const existingIndex = blueprints.findIndex(b => b.id === blueprint.id);

        const updatedBlueprint = {
            ...blueprint,
            updatedAt: new Date()
        };

        if (existingIndex >= 0) {
            blueprints[existingIndex] = updatedBlueprint;
        } else {
            blueprints.push(updatedBlueprint);
        }

        localStorage.setItem(STORAGE_KEY, JSON.stringify(blueprints));
        localStorage.setItem(CURRENT_PROJECT_KEY, blueprint.id);
    }

    /**
     * Load all blueprints from localStorage
     */
    static getAllBlueprints(): MechBlueprint[] {
        try {
            const data = localStorage.getItem(STORAGE_KEY);
            if (!data) return [];

            const parsed = JSON.parse(data);
            // Convert date strings back to Date objects
            return parsed.map((b: any) => ({
                ...b,
                createdAt: new Date(b.createdAt),
                updatedAt: new Date(b.updatedAt)
            }));
        } catch (error) {
            console.error('Failed to load blueprints:', error);
            return [];
        }
    }

    /**
     * Load a specific blueprint by ID
     */
    static loadBlueprint(id: string): MechBlueprint | undefined {
        const blueprints = this.getAllBlueprints();
        return blueprints.find(b => b.id === id);
    }

    /**
     * Get the last opened project ID
     */
    static getLastProjectId(): string | null {
        return localStorage.getItem(CURRENT_PROJECT_KEY);
    }

    /**
     * Delete a blueprint
     */
    static deleteBlueprint(id: string): void {
        const blueprints = this.getAllBlueprints().filter(b => b.id !== id);
        localStorage.setItem(STORAGE_KEY, JSON.stringify(blueprints));
    }

    /**
     * Export blueprint as JSON file
     */
    static exportAsJSON(blueprint: MechBlueprint): void {
        const dataStr = JSON.stringify(blueprint, null, 2);
        const blob = new Blob([dataStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${blueprint.name.replace(/\s+/g, '_')}_blueprint.json`;
        a.click();
        URL.revokeObjectURL(url);
    }

    /**
     * Export blueprint as Modelica model (basic structure)
     */
    static exportAsModelica(blueprint: MechBlueprint): void {
        let modelica = `model ${blueprint.name.replace(/\s+/g, '_')}\n`;
        modelica += `  // Generated by Mech SAF Lab v2.0\n`;
        modelica += `  // ${new Date().toISOString()}\n\n`;

        // Components
        blueprint.components.forEach(comp => {
            const type = comp.componentDefinitionId.split('.').pop() || 'Component';
            modelica += `  // ${comp.name}\n`;
            modelica += `  ${type} ${comp.name.replace(/\s+/g, '_')}(\n`;

            Object.entries(comp.parameterValues).forEach(([key, value], idx, arr) => {
                const comma = idx < arr.length - 1 ? ',' : '';
                modelica += `    ${key} = ${value}${comma}\n`;
            });

            modelica += `  );\n\n`;
        });

        // Connections
        modelica += `equation\n`;
        blueprint.connections.forEach(conn => {
            const src = blueprint.components.find(c => c.id === conn.sourceComponentId);
            const tgt = blueprint.components.find(c => c.id === conn.targetComponentId);
            if (src && tgt) {
                const srcName = src.name.replace(/\s+/g, '_');
                const tgtName = tgt.name.replace(/\s+/g, '_');
                modelica += `  connect(${srcName}.${conn.sourcePortId}, ${tgtName}.${conn.targetPortId});\n`;
            }
        });

        modelica += `end ${blueprint.name.replace(/\s+/g, '_')};\n`;

        const blob = new Blob([modelica], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${blueprint.name.replace(/\s+/g, '_')}.mo`;
        a.click();
        URL.revokeObjectURL(url);
    }

    /**
     * Import blueprint from JSON file
     */
    static async importFromJSON(file: File): Promise<MechBlueprint> {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();

            reader.onload = (e) => {
                try {
                    const content = e.target?.result as string;
                    const blueprint = JSON.parse(content) as MechBlueprint;

                    // Validate basic structure
                    if (!blueprint.id || !blueprint.components || !blueprint.connections) {
                        throw new Error('Invalid blueprint format');
                    }

                    // Generate new ID to avoid conflicts
                    blueprint.id = crypto.randomUUID();
                    blueprint.name = `${blueprint.name} (Imported)`;
                    blueprint.createdAt = new Date();
                    blueprint.updatedAt = new Date();

                    resolve(blueprint);
                } catch (error) {
                    reject(new Error('Failed to parse blueprint file'));
                }
            };

            reader.onerror = () => reject(new Error('Failed to read file'));
            reader.readAsText(file);
        });
    }

    /**
     * Export simulation results as CSV
     */
    static exportResultsAsCSV(variables: Record<string, number>, filename: string): void {
        let csv = 'Variable,Value\n';
        Object.entries(variables).forEach(([key, value]) => {
            csv += `"${key}",${value}\n`;
        });

        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${filename}_results.csv`;
        a.click();
        URL.revokeObjectURL(url);
    }

    /** Escape LaTeX special characters */
    private static escapeLaTeX(s: string | number): string {
        const str = String(s);
        return str
            .replace(/\\/g, '\\textbackslash{}')
            .replace(/[&%$#_{}]/g, '\\$&')
            .replace(/~/g, '\\textasciitilde{}')
            .replace(/\^/g, '\\textasciicircum{}');
    }

    /**
     * Export simulation results as LaTeX (tables for report/thesis)
     */
    static exportResultsAsLaTeX(blueprint: MechBlueprint, result: MechSimulationResult): void {
        const name = this.escapeLaTeX(blueprint.name.replace(/\s+/g, '_'));
        const date = new Date().toISOString().slice(0, 10);

        let tex = `% SAF Lab simulation results -- ${name}\n`;
        tex += `% Generated ${date}\n\n`;
        tex += `\\section{Simulation Results: ${this.escapeLaTeX(blueprint.name)}}\n\n`;

        if (result.metrics) {
            tex += `\\subsection{System Metrics}\n`;
            tex += `\\begin{tabular}{ll}\n`;
            tex += `\\hline\n\\textbf{Metric} & \\textbf{Value} \\\\\n\\hline\n`;
            const m = result.metrics;
            if (m.overallEfficiency != null) tex += `Overall efficiency & ${this.escapeLaTeX(m.overallEfficiency.toFixed(2))}\\% \\\\\n`;
            if (m.totalPowerInput != null) tex += `Total power input & ${this.escapeLaTeX(m.totalPowerInput.toFixed(2))} kW \\\\\n`;
            if (m.totalPowerOutput != null) tex += `Total power output & ${this.escapeLaTeX(m.totalPowerOutput.toFixed(2))} kW \\\\\n`;
            if (m.totalFlowRate != null) tex += `Total flow rate & ${this.escapeLaTeX(m.totalFlowRate.toFixed(2))} \\\\\n`;
            if (m.maxPressure != null) tex += `Max pressure & ${this.escapeLaTeX(m.maxPressure.toFixed(2))} \\\\\n`;
            if (m.pressureDrop != null) tex += `Pressure drop & ${this.escapeLaTeX(m.pressureDrop.toFixed(2))} \\\\\n`;
            if (m.totalHeatInput != null) tex += `Total heat input & ${this.escapeLaTeX(m.totalHeatInput.toFixed(2))} \\\\\n`;
            if (m.totalHeatOutput != null) tex += `Total heat output & ${this.escapeLaTeX(m.totalHeatOutput.toFixed(2))} \\\\\n`;
            tex += `\\hline\n\\end{tabular}\n\n`;
        }

        if (result.diagnostics?.convergence) {
            tex += `Converged: ${result.diagnostics.convergence.converged ? 'yes' : 'no'}; iterations: ${this.escapeLaTeX(String(result.diagnostics.convergence.iterations ?? 0))}.\n\n`;
        }

        if (result.variables && Object.keys(result.variables).length > 0) {
            tex += `\\subsection{Key Variables (sample)}\n`;
            tex += `\\begin{tabular}{ll}\n\\hline\n\\textbf{Variable} & \\textbf{Value} \\\\\n\\hline\n`;
            const entries = Object.entries(result.variables).slice(0, 25);
            entries.forEach(([k, v]) => {
                tex += `${this.escapeLaTeX(k)} & ${this.escapeLaTeX(Number(v).toFixed(4))} \\\\\n`;
            });
            tex += `\\hline\n\\end{tabular}\n`;
        }

        tex += `\n`;

        const blob = new Blob([tex], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${blueprint.name.replace(/\s+/g, '_')}_results.tex`;
        a.click();
        URL.revokeObjectURL(url);
    }
}
