import type { CodexThread, CodexMessage } from '../../hooks/useCodex';

export class CodexExportEngine {
    /**
     * Export a Codex thread and its messages to a Markdown document
     */
    static exportThreadToMarkdown(thread: CodexThread, messages: CodexMessage[]): string {
        let md = `# Codex Thread: ${thread.title}\n\n`;

        md += `**Thread ID:** \`${thread._id}\`  \n`;
        md += `**Created:** ${new Date(thread.createdAt).toLocaleString()}  \n`;
        md += `**Tags:** ${thread.tags.length > 0 ? thread.tags.map(t => `\`#${t}\``).join(' ') : 'None'}  \n\n`;

        md += `--- \n\n`;

        messages.forEach((msg, index) => {
            const author = msg.role === 'user' ? 'USER' : 'ELDORIA-AI';
            const timestamp = new Date(msg.createdAt).toLocaleString();

            md += `### [${timestamp}] ${author}\n\n`;
            md += `${msg.content}\n\n`;

            if (msg.attachments && msg.attachments.length > 0) {
                md += `**Attachments:**\n`;
                msg.attachments.forEach(att => {
                    md += `- ${att.fileName} (${att.type})\n`;
                });
                md += `\n`;
            }

            if (index < messages.length - 1) {
                md += `---\n\n`;
            }
        });

        md += `---\n`;
        md += `*Generated by Eldoria Neural Codex on ${new Date().toLocaleString()}*\n`;

        return md;
    }

    /**
     * Trigger browser download of the markdown file
     */
    static downloadThreadExport(thread: CodexThread, messages: CodexMessage[]): void {
        const content = this.exportThreadToMarkdown(thread, messages);
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);

        const filename = `codex_${thread.title.toLowerCase().replace(/\s+/g, '_')}_${thread._id.substring(0, 8)}.md`;

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();

        setTimeout(() => {
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }, 0);
    }
}
