
import { DynamicSimulationService } from '../services/physics/DynamicSimulationService'; // Adjust path
import { MechBlueprint } from '../types';
import { ComponentRegistry } from '../services/ComponentRegistry'; // Adjust path

// Mock BLUEPRINT that would be generated by saf_topology.json
const mockGearTrain: MechBlueprint = {
    id: 'verify_gear_train',
    name: 'Verification Gear Train',
    description: 'Motor -> Gear -> Load',
    domain: 'mechanical',
    version: '1.0.0',
    createdAt: new Date(),
    updatedAt: new Date(),
    author: 'ValidationScript',
    tags: ['test'],
    components: [
        {
            id: 'motor1',
            componentDefinitionId: 'mechanical.motor.electric', // Matches catalog
            name: 'Drive Motor',
            position: { x: 0, y: 0 },
            rotation: 0,
            parameterValues: {
                rated_power: 10,
                rated_speed: 1450,
                efficiency: 95
            },
            isSelected: false,
            groupIds: []
        },
        {
            id: 'gear1',
            componentDefinitionId: 'mechanical.gear.spur',
            name: 'Reduction Gear',
            position: { x: 100, y: 0 },
            rotation: 0,
            parameterValues: {
                z1: 20,
                z2: 60,
                efficiency: 98
            },
            isSelected: false,
            groupIds: []
        },
        {
            id: 'load1',
            componentDefinitionId: 'mechanical.bearing.ball', // Mock load
            name: 'Load Bearing',
            position: { x: 200, y: 0 },
            rotation: 0,
            parameterValues: {
                radial_load: 5,
                speed: 100 // dummy
            },
            isSelected: false,
            groupIds: []
        }
    ],
    connections: [
        {
            id: 'c1',
            sourceComponentId: 'motor1',
            sourcePortId: 'shaft_out',
            targetComponentId: 'gear1',
            targetPortId: 'shaft_in',
            type: 'mechanical',
            isSelected: false
        },
        {
            id: 'c2',
            sourceComponentId: 'gear1',
            sourcePortId: 'shaft_out',
            targetComponentId: 'load1',
            targetPortId: 'shaft',
            type: 'mechanical',
            isSelected: false
        }
    ],
    simulations: []
};

async function runVerification() {
    console.log("--- STARTING SAF PHYSICS VERIFICATION ---");

    // 1. Verify Component Loading
    const reg = ComponentRegistry.getInstance();
    const motorDef = reg.getComponent('mechanical.motor.electric');
    if (!motorDef?.physics) {
        console.error("[FAIL] Motor definition missing Physics Model!");
        process.exit(1);
    } else {
        console.log("[PASS] Motor has Physics Model.");
    }

    // 2. Run Dynamic Simulation
    try {
        console.log("Running Dynamic Simulation for 10s...");
        const result = await DynamicSimulationService.simulate(mockGearTrain, 10, 1.0);

        console.log(`[PASS] Simulation Completed. Duration: ${result.duration}ms`);
        console.log("Stats:", result.diagnostics.convergence);

        // Check Variables
        // Expected: Motor Speed ~1450, Gear Out ~ 1450/3 = 483.33
        // Note: The Solver might not solve correctly if we don't have a LOAD CURVE.
        // But let's check what variables are emitted.
        console.log("Final Variables:", result.variables);

        const motorSpeed = result.variables['motor1_speed'] || result.variables['motor1_omega'];

        if (motorSpeed) {
            console.log(`Motor Speed Evaluated: ${motorSpeed}`);
        } else {
            console.log("Note: Speed variable might be named differently in output.");
        }

    } catch (e) {
        console.error("[FAIL] Simulation Error:", e);
    }
}

runVerification();
